[package]
name = "ils"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ils-bin"
path = "src/main.rs"

[dependencies]
crossterm = "0.28"
syntect = "5.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
image = "0.25"
viuer = "0.7"
pdf-extract = "0.7"
