# Interactive ls (ils) - Color Configuration
# Edit this file to customize colors
# After editing, copy to ~/.config/ils/colors.toml

# Color options:
#   - Named: black, red, green, yellow, blue, magenta, cyan, white
#            darkgrey/darkgray, darkred, darkgreen, darkyellow, darkblue, darkmagenta, darkcyan, grey/gray
#   - Hex: #RRGGBB or #RGB (e.g., "#00ff00" or "#0f0")
#   - Special: "reverse" (inverted colors), "none" (no color)

# Path bar
path_fg = "white"
path_bg = "#333333"

# Selected item
selected_fg = "none"
selected_bg = "none"

# Directory names
directory_fg = "cyan"

# Preview pane border
preview_border_fg = "darkgrey"
