# Interactive ls (ils) - Keybindings Configuration
# Edit this file to customize your keybindings
# After editing, copy to ~/.config/ils/keybindings.toml

up = ['w']
down = ['s']
left = ['a']
right = ['d']
open = ['l']
back = ['j', 'b']
home = ['h']
select = [' ']
quit = ['q']
help = ['?']
preview_toggle = ['p']
preview_up = ['i']
preview_down = ['o']
preview_height_decrease = ['-', '_']
preview_height_increase = ['+', '=']
